import {initializeApp} from 'https://www.gstatic.com/firebasejs/12.4.0/firebase-app.js';
import {multiFactor,TotpMultiFactorGenerator,getMultiFactorResolver,getAuth,setPersistence,browserSessionPersistence,onAuthStateChanged,createUserWithEmailAndPassword,signInWithEmailAndPassword,sendEmailVerification,sendPasswordResetEmail,signOut,GoogleAuthProvider,signInWithPopup,RecaptchaVerifier,signInWithPhoneNumber} from 'https://www.gstatic.com/firebasejs/12.4.0/firebase-auth.js';
import {getFirestore,doc,getDoc,setDoc,onSnapshot,collection,query,orderBy,limit,startAfter,getDocs,writeBatch,serverTimestamp} from 'https://www.gstatic.com/firebasejs/12.4.0/firebase-firestore.js';
import {initializeAppCheck,ReCaptchaEnterpriseProvider} from 'https://www.gstatic.com/firebasejs/12.4.0/firebase-app-check.js';
import {firebaseConfig,ADMIN_UID,APP_CHECK_SITE_KEY} from './firebase-config.js';
const app=initializeApp(firebaseConfig),auth=getAuth(app),store=getFirestore(app);
if(APP_CHECK_SITE_KEY)initializeAppCheck(app,{provider:new ReCaptchaEnterpriseProvider(APP_CHECK_SITE_KEY),isTokenAutoRefreshEnabled:true});
auth.languageCode='ko';
await setPersistence(auth,browserSessionPersistence);
const gate=document.getElementById('auth-gate'),shell=document.getElementById('app-shell'),message=document.getElementById('auth-message');
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let memberCursor=null;let stopProfile=()=>{},stopData=()=>{},confirmation,verifier,mode='login',epoch=0;
const fail=e=>{if(e.code==='auth/multi-factor-auth-required'){mfaChallenge(e);return;}const code=typeof e.code==='string'?e.code:'unknown';const hints={'auth/invalid-credential':'이메일 또는 비밀번호를 확인해주세요.','auth/wrong-password':'이메일 또는 비밀번호를 확인해주세요.','auth/user-not-found':'이메일 또는 비밀번호를 확인해주세요.','auth/email-already-in-use':'이미 가입된 이메일입니다.','auth/operation-not-allowed':'Firebase에서 이메일/비밀번호 등 해당 로그인 방식을 활성화해주세요.','auth/unauthorized-domain':'Firebase 승인 도메인에 현재 앱 도메인을 추가해주세요.','auth/network-request-failed':'네트워크 연결 또는 브라우저의 요청 차단을 확인해주세요.','auth/invalid-app-credential':'앱 인증 정보 검증에 실패했습니다. App Check 및 reCAPTCHA 설정을 확인해주세요.','auth/user-disabled':'이 계정은 이용이 중지되었습니다.','auth/too-many-requests':'요청이 많습니다. 잠시 후 다시 시도해주세요.','auth/internal-error':'인증 처리 오류입니다. 브라우저 개발자 도구의 실패 요청을 확인해주세요.','auth/invalid-api-key':'Firebase 웹 설정의 API 키를 확인해주세요.','auth/popup-blocked':'브라우저의 로그인 팝업을 허용해주세요.','permission-denied':'보안 규칙·회원 승인 상태·App Check 적용 설정을 확인해주세요.'};message.textContent=(hints[code]||'요청을 완료하지 못했습니다. 오류 코드를 관리자에게 전달해주세요.')+' [오류 코드: '+code+']';};
function mfaChallenge(error){const resolver=getMultiFactorResolver(auth,error),hint=resolver.hints.find(x=>x.factorId==='totp');if(!hint){message.textContent='TOTP 인증 수단이 필요합니다.';return;}gate.querySelector('#auth-fields').innerHTML='<h1>2단계 인증</h1><form id="mfa-form"><label>인증 앱의 6자리 코드<input name="code" inputmode="numeric" pattern="[0-9]{6}" required></label><button>인증</button></form>';document.getElementById('mfa-form').onsubmit=async e=>{e.preventDefault();try{await resolver.resolveSignIn(TotpMultiFactorGenerator.assertionForSignIn(hint.uid,new FormData(e.target).get('code')));}catch(err){fail(err);}};}
async function enrollAdmin(user){status(user,'관리자 2단계 인증 설정');message.textContent='Firebase Identity Platform에서 TOTP를 활성화한 뒤 진행해주세요.';const b=document.createElement('button');b.textContent='인증 앱 연결';gate.querySelector('#auth-fields').append(b);b.onclick=async()=>{try{const secret=await TotpMultiFactorGenerator.generateSecret(await multiFactor(user).getSession());const box=document.createElement('div');box.innerHTML='<p>Google Authenticator 등에서 아래 설정 키를 직접 등록하세요. 키를 다른 사람에게 공유하지 마세요.</p><code id="totp-secret"></code><form id="enroll-form"><label>6자리 인증 코드<input name="code" inputmode="numeric" pattern="[0-9]{6}" required></label><button>등록 완료</button></form>';gate.querySelector('#auth-fields').append(box);box.querySelector('#totp-secret').textContent=secret.secretKey;b.disabled=true;box.querySelector('form').onsubmit=async e=>{e.preventDefault();try{await multiFactor(user).enroll(TotpMultiFactorGenerator.assertionForEnrollment(secret,new FormData(e.target).get('code')),'관리자 인증 앱');await signOut(auth);message.textContent='등록했습니다. 다시 로그인하여 2단계 인증을 완료해주세요.';}catch(err){fail(err);}};}catch(e){fail(e);}};}
function hide(){document.getElementById('admin-panel').hidden=true;shell.hidden=true;gate.hidden=false;window.assetCloud=null;window.dispatchEvent(new Event('asset-lock'));}
function login(){gate.querySelector('#auth-fields').innerHTML=`<h1>자산과투자사이</h1><p>로그인하고 나의 자산을 관리하세요.</p><div class="auth-tabs"><button id="login-tab">로그인</button><button id="signup-tab">이메일 가입</button></div><form id="email-form"><label>이메일<input type="email" name="email" autocomplete="email" required></label><label>비밀번호<input type="password" name="password" autocomplete="${mode==='signup'?'new-password':'current-password'}" minlength="${mode==='signup'?12:1}" required></label>${mode==='signup'?'<p>이메일 인증 후 이름·동의 항목을 작성합니다.</p>':''}<button class="primary">${mode==='signup'?'가입 신청':'로그인'}</button></form><button id="google-login">Google 계정으로 계속</button><details><summary>전화번호로 계속</summary><p>인증용 번호는 Google에 전송·저장됩니다.</p><form id="phone-form"><label>휴대폰 번호<input name="phone" type="tel" placeholder="+821012345678" pattern="\\+[1-9][0-9]{7,14}" required></label><label class="check"><input type="checkbox" required>전화번호 인증 안내 확인</label><div id="recaptcha"></div><button>인증 문자 받기</button></form><form id="code-form" hidden><label>인증번호<input name="code" inputmode="numeric" pattern="[0-9]{6}" required></label><button>인증 확인</button></form></details><button id="reset-password">비밀번호 재설정 메일</button>`;
verifier?.clear();verifier=null;
document.getElementById('login-tab').onclick=()=>{mode='login';login();};document.getElementById('signup-tab').onclick=()=>{mode='signup';login();};
document.getElementById('email-form').onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;message.textContent='';const d=new FormData(e.target);try{if(mode==='signup'){const {user}=await createUserWithEmailAndPassword(auth,d.get('email'),d.get('password'));await requestVerification(user);}else await signInWithEmailAndPassword(auth,d.get('email'),d.get('password'));}catch(err){fail(err);}finally{b.disabled=false;}};
document.getElementById('google-login').onclick=async()=>{try{await signInWithPopup(auth,new GoogleAuthProvider());}catch(e){fail(e);}};
document.getElementById('reset-password').onclick=async()=>{const email=document.querySelector('[name=email]').value;if(!email){message.textContent='이메일을 먼저 입력해주세요.';return;}try{await sendPasswordResetEmail(auth,email);message.textContent='등록된 주소라면 재설정 메일을 확인해주세요.';}catch(e){fail(e);}};
document.getElementById('phone-form').onsubmit=async e=>{e.preventDefault();e.submitter.disabled=true;try{verifier??=new RecaptchaVerifier(auth,'recaptcha',{});confirmation=await signInWithPhoneNumber(auth,new FormData(e.target).get('phone'),verifier);document.getElementById('code-form').hidden=false;message.textContent='인증 문자를 확인해주세요.';}catch(err){verifier?.clear();verifier=null;fail(err);}finally{e.submitter.disabled=false;}};
document.getElementById('code-form').onsubmit=async e=>{e.preventDefault();try{await confirmation.confirm(new FormData(e.target).get('code'));}catch(err){fail(err);}};}
const verificationSentAt=new Map();
async function requestVerification(user,button){
const last=verificationSentAt.get(user.uid)||0;
if(Date.now()-last<60000){message.textContent='인증 메일을 이미 요청했습니다. 1분 후 다시 시도해주세요.';return;}
if(button)button.disabled=true;
message.textContent='인증 메일 발송 요청 중입니다.';
try{
await sendEmailVerification(user);
verificationSentAt.set(user.uid,Date.now());
message.textContent=user.email+' 주소로 인증 메일 발송 요청이 접수되었습니다. 수신함·스팸함·전체보관함을 확인해주세요. 실제 도착 여부는 앱에서 확인할 수 없습니다.';
if(button)setTimeout(()=>{if(button.isConnected)button.disabled=false;},60000);
}catch(error){if(button)button.disabled=false;throw error;}
}
function status(user,text){gate.querySelector('#auth-fields').innerHTML=`<h1>${text}</h1><p>${escape(user.email||user.phoneNumber)}</p><button id="refresh-auth">상태 새로고침</button>${user.email&&!user.emailVerified?'<button id="verify-email">인증 메일 다시 보내기</button>':''}<button id="gate-logout">로그아웃</button>`;document.getElementById('refresh-auth').onclick=()=>location.reload();document.getElementById('gate-logout').onclick=()=>signOut(auth);document.getElementById('verify-email')?.addEventListener('click',async event=>{try{await requestVerification(user,event.currentTarget);}catch(e){fail(e);}});}
async function profileForm(user){gate.querySelector('#auth-fields').innerHTML=`<h1>가입 정보 작성</h1><p>가입 신청 후 관리자 승인이 필요합니다.</p><form id="profile-form"><label>이름 또는 닉네임<input name="name" maxlength="80" required></label><label class="check"><input type="checkbox" required><a href="./privacy.html" target="_blank" rel="noopener">개인정보 수집·이용 안내</a> 확인 및 동의</label><button class="primary">가입 신청</button></form><button id="gate-logout">로그아웃</button>`;document.getElementById('gate-logout').onclick=()=>signOut(auth);document.getElementById('profile-form').onsubmit=async e=>{e.preventDefault();e.submitter.disabled=true;try{await setDoc(doc(store,'members',user.uid),{name:new FormData(e.target).get('name').trim(),email:user.email||'',phone:user.phoneNumber||'',status:'pending',consentVersion:'2026-10-07',createdAt:serverTimestamp(),updatedAt:serverTimestamp()});}catch(err){fail(err);e.submitter.disabled=false;}};}
async function unlock(user){const token=epoch;status(user,'자산 불러오는 중');const ref=doc(store,'portfolios',user.uid);window.assetCloud={save:async data=>{if(token!==epoch)throw Error('세션이 변경되었습니다.');await setDoc(ref,{data,updatedAt:serverTimestamp()});}};
stopData=onSnapshot(ref,snap=>{if(token!==epoch||snap.metadata.hasPendingWrites)return;shell.hidden=false;gate.hidden=true;document.getElementById('account-name').textContent=user.email||user.phoneNumber||'회원';document.getElementById('admin-open').hidden=user.uid!==ADMIN_UID;window.dispatchEvent(new CustomEvent('asset-load',{detail:snap.exists()?snap.data().data:null}));},err=>{hide();fail(err);});}
onAuthStateChanged(auth,async user=>{epoch++;const authEpoch=epoch;stopProfile();stopData();hide();message.textContent='';if(!user){login();return;}if(!user.emailVerified&&!user.phoneNumber){status(user,'이메일 인증이 필요합니다');return;}
if(user.uid===ADMIN_UID){const result=await user.getIdTokenResult(true);if(epoch!==authEpoch)return;if(!result.claims.firebase?.sign_in_second_factor){if(multiFactor(user).enrolledFactors.length){status(user,'2단계 인증으로 다시 로그인해주세요');return;}await enrollAdmin(user);return;}}
stopProfile=onSnapshot(doc(store,'members',user.uid),async snap=>{epoch++;stopData();hide();if(!snap.exists()){await profileForm(user);return;}const p=snap.data();if(user.uid===ADMIN_UID||p.status==='approved'){await unlock(user);}else status(user,({pending:'관리자 승인 대기',rejected:'가입 신청이 거절되었습니다',suspended:'이용이 정지되었습니다'})[p.status]||'가입 상태 확인 필요');},fail);});
document.getElementById('logout').onclick=()=>signOut(auth);
async function openAdmin(next=false){const panel=document.getElementById('admin-panel');panel.hidden=false;panel.scrollIntoView({behavior:'smooth'});panel.innerHTML='<h2>회원 관리</h2><button id="admin-close">닫기</button><button id="admin-audit">처리 이력</button><div id="member-list">불러오는 중</div><button id="admin-next" hidden>다음 회원 100명</button>';document.getElementById('admin-close').onclick=()=>panel.hidden=true;try{const rows=await getDocs(query(collection(store,'members'),orderBy('createdAt','desc'),...(next&&memberCursor?[startAfter(memberCursor)]:[]),limit(100)));memberCursor=rows.docs.at(-1);document.getElementById('admin-next').hidden=rows.size<100;document.getElementById('admin-next').onclick=()=>openAdmin(true);document.getElementById('admin-audit').onclick=async()=>{try{const events=await getDocs(query(collection(store,'audit'),orderBy('at','desc'),limit(100)));document.getElementById('member-list').innerHTML=events.docs.map(d=>{const x=d.data();return `<article><p>${escape(x.target)} · ${escape(x.status)}</p><p>${escape(x.at?.toDate().toLocaleString('ko-KR'))}</p></article>`;}).join('')||'처리 이력이 없습니다.';document.getElementById('admin-next').hidden=true;}catch(e){fail(e);}};document.getElementById('member-list').innerHTML=rows.docs.map(d=>{const m=d.data();return `<article><strong>${escape(m.name)}</strong><p>${escape(m.email||m.phone)} · ${escape(m.status)}</p>${d.id===ADMIN_UID?'<p>최초 관리자</p>':['approved','rejected','suspended'].map(v=>`<button data-member="${d.id}" data-status="${v}">${({approved:'승인',rejected:'거절',suspended:'정지'})[v]}</button>`).join('')}</article>`;}).join('')||'신청한 회원이 없습니다.';panel.querySelectorAll('[data-member]').forEach(b=>b.onclick=async()=>{if(!confirm('회원 상태를 변경할까요?'))return;try{const batch=writeBatch(store),event=doc(collection(store,'audit'));batch.update(doc(store,'members',b.dataset.member),{status:b.dataset.status,updatedAt:serverTimestamp(),lastActionId:event.id});batch.set(event,{actor:auth.currentUser.uid,target:b.dataset.member,status:b.dataset.status,at:serverTimestamp()});await batch.commit();document.getElementById('admin-open').click();}catch(e){fail(e);alert('처리하지 못했습니다. 보안 규칙을 확인해주세요.');}});}catch(e){document.getElementById('member-list').textContent='회원 목록을 불러오지 못했습니다.';fail(e);}}
document.getElementById('admin-open').onclick=()=>openAdmin();
let idle;const resetIdle=()=>{clearTimeout(idle);if(auth.currentUser)idle=setTimeout(()=>signOut(auth),30*60*1000);};['pointerdown','keydown'].forEach(t=>document.addEventListener(t,resetIdle,{passive:true}));onAuthStateChanged(auth,resetIdle);
