import {readFileSync} from 'node:fs';
import {test,before,after,beforeEach} from 'node:test';
import {initializeTestEnvironment,assertFails,assertSucceeds} from '@firebase/rules-unit-testing';
import {doc,getDoc,setDoc,updateDoc,deleteDoc,getDocs,collection,query,limit,writeBatch,serverTimestamp} from 'firebase/firestore';
let env;const adminUid='Y56JWvSynpfT0H2WNJ2agxwpzdE3';
before(async()=>{env=await initializeTestEnvironment({projectId:'demo-jasan-invest',firestore:{rules:readFileSync('firebase/firestore.rules','utf8')}});});
after(async()=>{await env?.cleanup();});beforeEach(async()=>{await env.clearFirestore();await env.withSecurityRulesDisabled(async ctx=>{for(const [uid,status] of [['alice','approved'],['bob','pending'],[adminUid,'pending']])await setDoc(doc(ctx.firestore(),'members',uid),{name:uid,email:uid+'@example.com',phone:'',status,consentVersion:'2026-10-07',createdAt:new Date(),updatedAt:new Date()});});});
const db=(uid,verified=false)=>env.authenticatedContext(uid,{email:uid+'@example.com',email_verified:verified,firebase:{}}).firestore();
const payload=()=>({data:{version:1,demo:false,accounts:[],holdings:[],debts:[],transactions:[],income:[],goals:[],flows:[],history:[],alerts:[]},updatedAt:serverTimestamp()});
test('anonymous users cannot access member records; unverified users can read their own profile',async()=>{await assertFails(getDoc(doc(env.unauthenticatedContext().firestore(),'members','alice')));await assertSucceeds(getDoc(doc(db('alice',false),'members','alice')));});
test('approved member can write own portfolio but not another member portfolio',async()=>{await assertSucceeds(setDoc(doc(db('alice'),'portfolios','alice'),payload()));await assertFails(getDoc(doc(db('bob'),'portfolios','alice')));await assertFails(setDoc(doc(db('alice'),'portfolios','bob'),payload()));await assertFails(getDoc(doc(db(adminUid),'portfolios','alice')));});
test('pending and suspended members cannot write portfolios',async()=>{await assertFails(setDoc(doc(db('bob'),'portfolios','bob'),payload()));await env.withSecurityRulesDisabled(ctx=>updateDoc(doc(ctx.firestore(),'members','alice'),{status:'suspended'}));await assertFails(setDoc(doc(db('alice'),'portfolios','alice'),payload()));});
test('user cannot approve self or add admin role',async()=>{await assertFails(updateDoc(doc(db('bob'),'members','bob'),{status:'approved',updatedAt:serverTimestamp()}));await assertFails(updateDoc(doc(db('alice'),'members','alice'),{admin:true}));});
test('new member must start pending, with authenticated identity and timestamps',async()=>{const profile={name:'신규',email:'new@example.com',phone:'',status:'pending',consentVersion:'2026-10-07',createdAt:serverTimestamp(),updatedAt:serverTimestamp()};await assertFails(setDoc(doc(db('new'),'members','new'),{...profile,status:'approved'}));await assertFails(setDoc(doc(db('new'),'members','new'),{...profile,email:'fake@example.com'}));await assertSucceeds(setDoc(doc(db('new'),'members','new'),profile));});
test('admin approval requires atomic audit event, audit cannot be altered',async()=>{const a=db(adminUid);await assertFails(updateDoc(doc(a,'members','bob'),{status:'approved',updatedAt:serverTimestamp()}));const batch=writeBatch(a);batch.update(doc(a,'members','bob'),{status:'approved',updatedAt:serverTimestamp(),lastActionId:'e1'});batch.set(doc(a,'audit','e1'),{actor:adminUid,target:'bob',status:'approved',at:serverTimestamp()});await assertSucceeds(batch.commit());await assertFails(deleteDoc(doc(a,'audit','e1')));await assertSucceeds(setDoc(doc(db('bob'),'portfolios','bob'),payload()));});
test('only admin can list members with capped query',async()=>{await assertFails(getDocs(query(collection(db('alice'),'members'),limit(100))));await assertSucceeds(getDocs(query(collection(db(adminUid),'members'),limit(100))));});

test('first-factor administrator without email verification can access own portfolio and member list',async()=>{const a=env.authenticatedContext(adminUid,{email_verified:false,firebase:{}}).firestore();await assertSucceeds(getDocs(query(collection(a,'members'),limit(100))));await assertSucceeds(setDoc(doc(a,'portfolios',adminUid),payload()));});

test('unverified regular member cannot acquire administrative privileges',async()=>{await assertFails(getDocs(query(collection(db('alice',false),'members'),limit(100))));});
